server:
  host: 0.0.0.0
  port: 8080

backends:
  - address: localhost
    port: 3001
    weight: 1
  - address: localhost
    port: 3002
    weight: 1
  - address: localhost
    port: 3003
    weight: 1

app:
  environment: "development"
  log_level: "debug"
